name: food_mama
description: FoodMama Multi-Restaurants flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  curved_navigation_bar: ^0.3.3
  flutter_spinkit: ^4.1.2+1
  mvc_pattern: ^8.0.0
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  google_sign_in: ^4.5.9
  flutter_signin_button: ^2.0.0
  datetime_picker_formfield: ^1.0.0
  shimmer: ^1.1.1
  avatar_glow: ^1.2.0
  country_code_picker: ^1.3.14
  overlay_support: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path_android: "assets/custom_images/app_icon.png"
  image_path_ios: "assets/custom_images/app_icon.png"
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/custom_images/
    - assets/custom_images/bottom_navbabr_icons/
    - assets/custom_images/ordered_food_images/
    - assets/custom_images/0.75x/
    - assets/custom_images/1.5x/
    - assets/custom_images/1x/
    - assets/custom_images/2x/
    - assets/custom_images/3x/
    - assets/custom_images/4x/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/custom_fonts/Metropolis-Black.otf
        - asset: assets/custom_fonts/Metropolis-BlackItalic.otf
        - asset: assets/custom_fonts/Metropolis-Bold.otf
        - asset: assets/custom_fonts/Metropolis-BoldItalic.otf
        - asset: assets/custom_fonts/Metropolis-ExtraBold.otf
        - asset: assets/custom_fonts/Metropolis-ExtraBoldItalic.otf
        - asset: assets/custom_fonts/Metropolis-ExtraLight.otf
        - asset: assets/custom_fonts/Metropolis-ExtraLightItalic.otf
        - asset: assets/custom_fonts/Metropolis-LightItalic.otf
        - asset: assets/custom_fonts/Metropolis-MediumItalic.otf
        - asset: assets/custom_fonts/Metropolis-Regular.otf
        - asset: assets/custom_fonts/Metropolis-RegularItalic.otf
        - asset: assets/custom_fonts/Metropolis-SemiBold.otf
        - asset: assets/custom_fonts/Metropolis-SemiBoldItalic.otf
        - asset: assets/custom_fonts/Metropolis-ThinItalic.otf
